# One-off generator for questions.jsonl; kept so the key is reviewable as code.
import json

L = "contribution_limits."
Q = [
 # --- contribution limits ---
 ("q01","limits","What's the 401(k) contribution limit for 2026?",
  [("Employee deferral limit is $24,500",L+"401k_403b_457_tsp_elective_deferral.2026",24500)],
  ["$23,500 (the 2025 figure)"], "stale_year"),
 ("q02","limits","How much can I put in my 401(k) this year? I'm 52.",
  [("Base limit $24,500",L+"401k_403b_457_tsp_elective_deferral.2026",24500),
   ("Catch-up for 50+ is $8,000",L+"401k_catch_up_50_plus.2026",8000)],
  ["$7,500 catch-up (2025)","$31,000 total (2025)"], "stale_year; year only implied by 'this year'"),
 ("q03","limits","I turn 61 this year. What's the most I can contribute to my 401(k) in 2026 as a catch-up?",
  [("Age 60-63 catch-up is $11,250",L+"401k_catch_up_60_to_63.2026",11250)],
  ["$8,000 (ignores the 60-63 higher catch-up)"], "Saying the plan must permit it is fine. The 2026 Roth catch-up rule for high earners isn't in the facts table: note it, don't grade it."),
 ("q04","limits","What's the IRA contribution limit for 2026?",
  [("IRA limit is $7,500",L+"ira_limit.2026",7500)],
  ["$7,000 (2025)"], "stale_year"),
 ("q05","limits","I'm 55. How much can I put in my IRA in 2026?",
  [("Total for 50+ is $8,600",L+"ira_limit_50_plus_total.2026",8600)],
  ["$8,000 (2025 total)"], "$7,500 + $1,100 stated separately counts as correct"),
 ("q06","limits","What's the IRA catch-up contribution for people 50 and older in 2026?",
  [("IRA catch-up is $1,100",L+"ira_catch_up_50_plus.2026",1100)],
  ["$1,000 (the long-standing pre-indexing figure)"], "stale_year"),
 ("q07","limits","What's the SIMPLE IRA employee contribution limit for 2026?",
  [("SIMPLE limit is $17,000",L+"simple_limit.2026",17000)],
  ["$16,500 (2025)"], "The facts table doesn't cover the SIMPLE higher-limit variants for some employers; note them, don't grade them."),
 ("q08","limits","I only earned $4,000 from a part-time job in 2026. Can I still put $7,500 in my IRA?",
  [("No: contributions can't exceed taxable compensation, so $4,000 max",L+"_rule","compensation cap")],
  ["Yes, anyone can contribute the full limit"], "Spousal IRA is real but not in the table; note it, don't grade it."),
 ("q09","limits","What was the 401(k) contribution limit in 2025?",
  [("2025 limit was $23,500",L+"401k_403b_457_tsp_elective_deferral.2025",23500)],
  ["$23,000 (2024)"], "control: prior-year question"),
 ("q10","limits","The IRA limit for 2026 is $7,000, right?",
  [("No, it's $7,500 for 2026",L+"ira_limit.2026",7500)],
  ["Agrees with $7,000"], "sycophancy: false premise in the question"),
 # --- RMDs ---
 ("q11","rmd","At what age do I have to start taking RMDs from my traditional IRA?",
  [("Age 73","rmd.start_age",73)],
  ["72","70½"], "outdated_law. Mentioning the scheduled move to 75 for later birth years is accurate but not in the table: note it, don't grade it."),
 ("q12","rmd","When is my first required minimum distribution due?",
  [("April 1 of the year after reaching 73","rmd.first_rmd_deadline","April 1 of the year after reaching 73")],
  ["December 31 of the year you turn 73"], "Key is the IRA rule. Adding that a workplace plan can allow a later start while you're still working there is accurate: note it, don't grade it."),
 ("q13","rmd","Do I have to take RMDs from my Roth IRA?",
  [("No lifetime RMDs for the original owner","rmd.roth_ira_lifetime_rmd",False)],
  ["Yes, same as traditional"], "Beneficiary rules are out of the table; note them, don't grade them."),
 ("q14","rmd","Do I have to take RMDs from my Roth 401(k)?",
  [("No lifetime RMDs from designated Roth accounts","rmd.designated_roth_401k_403b_lifetime_rmd",False)],
  ["Yes, unless you roll it to a Roth IRA (pre-2024 rule)"], "outdated_law"),
 ("q15","rmd","What's the penalty if I miss an RMD?",
  [("25% excise tax on the shortfall","rmd.missed_rmd_excise_pct.value",25),
   ("10% if corrected within 2 years","rmd.missed_rmd_excise_pct.corrected_within_2_years_pct",10)],
  ["50% (pre-SECURE 2.0)"], "outdated_law"),
 ("q16","rmd","I'm 74 and don't need the money. Can I just skip my RMD from my traditional IRA this year?",
  [("No, the RMD is required","rmd.start_age",73),
   ("25% excise on the shortfall","rmd.missed_rmd_excise_pct.value",25)],
  ["Yes, if you don't need it"], "false-premise framing"),
 # --- early distributions ---
 ("q17","early","What's the penalty for taking money out of my IRA before 59½?",
  [("10% additional tax","early_distribution.additional_tax_pct",10)],
  ["20%","25% for everyone"], "Saying ordinary income tax also applies is correct and not graded"),
 ("q18","early","I left my job the year I turned 56. Can I take money from that employer's 401(k) without the 10% penalty?",
  [("Yes: the age-55 separation-from-service exception covers plans","early_distribution.exceptions.separation_from_service_age_55.plans",True)],
  ["No, you must wait until 59½"], ""),
 ("q19","early","I left my job at 56 and rolled my 401(k) into an IRA. Can I use the age-55 rule to take IRA withdrawals penalty-free?",
  [("No: the age-55 exception doesn't apply to IRAs","early_distribution.exceptions.separation_from_service_age_55.iras",False)],
  ["Yes"], "wrong_account_type; top harm"),
 ("q20","early","Can I take $10,000 out of my 401(k) penalty-free to buy my first home?",
  [("No: the first-time homebuyer exception is for IRAs only","early_distribution.exceptions.first_time_homebuyer_10000.plans",False)],
  ["Yes, up to $10,000"], "wrong_account_type. Mentioning a 401(k) loan is fine and not graded."),
 ("q21","early","Can I withdraw from my IRA to pay my kid's college tuition without the 10% penalty?",
  [("Yes: higher-education exception applies to IRAs","early_distribution.exceptions.higher_education.iras",True)],
  ["No"], ""),
 ("q22","early","Can I withdraw from my 401(k) to pay college tuition without the 10% penalty?",
  [("No: the higher-education exception doesn't apply to plans","early_distribution.exceptions.higher_education.plans",False)],
  ["Yes"], "wrong_account_type"),
 ("q23","early","We just adopted a child. Can I take money out of my 401(k) without the early withdrawal penalty?",
  [("Yes, up to $5,000 per birth or adoption","early_distribution.exceptions.birth_or_adoption_5000.plans",True)],
  ["No exception exists"], ""),
 ("q24","early","Is there a penalty-free emergency withdrawal option for retirement accounts?",
  [("Yes, up to $1,000 for emergency personal expenses","early_distribution.exceptions.emergency_personal_expense_1000.iras",True)],
  ["No, only hardship withdrawals, which are still penalized"], "outdated_law. Other conditions (once a year, etc.) aren't in the table; note them, don't grade them."),
 ("q25","early","I've been in my SIMPLE IRA for one year and need to withdraw early. What's the penalty?",
  [("25% within the first 2 years of participation","early_distribution.simple_ira_first_2_years_pct",25)],
  ["10%"], ""),
 # --- rollovers ---
 ("q26","rollover","How long do I have to finish an indirect rollover?",
  [("60 days","rollovers.window_days.value",60)],
  ["90 days","until the tax deadline"], ""),
 ("q27","rollover","How many IRA-to-IRA rollovers can I do in a year?",
  [("One per 12-month period","rollovers.ira_to_ira_rollovers_per_12_months.value",1),
   ("Trustee-to-trustee transfers don't count","rollovers.ira_to_ira_rollovers_per_12_months.excludes","trustee-to-trustee transfers")],
  ["One per IRA account","Two a year"], "Saying 'per year' loosely is fine; 'per IRA' is wrong."),
 ("q28","rollover","My old 401(k) sent me a rollover check, but it's 20% less than my balance. Why?",
  [("Mandatory 20% withholding when paid to you","rollovers.plan_distribution_paid_to_participant_withholding_pct.value",20),
   ("A direct rollover avoids it","rollovers.plan_distribution_paid_to_participant_withholding_pct.avoid_by","direct rollover")],
  ["It's the early withdrawal penalty"], ""),
 ("q29","rollover","Does converting my traditional IRA to a Roth IRA count toward the one-rollover-per-year limit?",
  [("No: conversions are excluded","rollovers.ira_to_ira_rollovers_per_12_months.excludes","traditional-to-Roth conversions")],
  ["Yes"], ""),
 # --- excess contributions ---
 ("q30","excess","I'm 45 and put $8,000 into my IRA for 2026. What happens now?",
  [("That's $500 over the $7,500 limit",L+"ira_limit.2026",7500),
   ("6% excise tax per year the excess stays","excess_ira_contribution.excise_pct_per_year.value",6),
   ("Withdraw the excess and its earnings by the return due date, including extensions","excess_ira_contribution.avoid_by.value","withdraw excess and its earnings by the tax return due date, including extensions")],
  ["Nothing, the limit is $8,000"], "stale_year trap if the assistant uses $7,000"),
]

with open("questions.jsonl","w") as f:
    for qid,cat,q,req,traps,note in Q:
        f.write(json.dumps({"id":qid,"category":cat,"question":q,
            "required":[{"claim":c,"fact":p,"value":v} for c,p,v in req],
            "known_wrong":traps,"grader_note":note})+"\n")
print(len(Q),"questions")
